### ISSUE TITLE
Safari and webKitAudioContext

### ISSUE THREAD

**Issue by jamesopstad** [bbc/r-audio#2]
This is a great library and just what I was looking for to better integrate Web Audio with React. At the moment, however, is doesn't work at all with Safari as this still uses webKitAudioContext and has various other differences with the spec. You may want to look at https://github.com/cwilso/AudioContext-MonkeyPatch/ if you're interested in cross browser compatibility.

**Comment by jakubfiala-bbc** [comment]
Hey @jamesopstad – sorry for replying so late, for some reason I didn't get an email notification for this. Thanks for pointing this out, I'll fix this right away and let you know once it's published!

**Comment by jakubfiala-bbc** [comment]
@jamesopstad this should now be fixed in *r-audio* v1.2.0 and published on npm. Please bear in mind a lot of the nodes *r-audio* supports are not supported in Safari, so you may have trouble running some of the examples.
